global:
  scrape_interval: 15s # intervalo de busca na fonte de dados

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889'] # Nome do servi√ßo no docker-compose + porta do exporter